# Generated by Django 2.0.5 on 2018-05-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20180504_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='restaurants.Ingredient', verbose_name='Ingredients'),
        ),
    ]
