# Generated by Django 2.0.5 on 2018-08-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_auto_20180803_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='/static/', upload_to='restaurants_images/ '),
        ),
    ]
