# Generated by Django 2.0.5 on 2018-08-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_auto_20180803_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurants_images/default.png', null=True, upload_to='restaurants_images'),
        ),
    ]
