# Generated by Django 2.0.5 on 2018-08-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='places',
            new_name='seates',
        ),
    ]
