# Generated by Django 2.0.5 on 2018-08-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_type', to='menu.DishType'),
        ),
    ]
