# Generated by Django 2.0.5 on 2018-08-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180821_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.CharField(blank=True, help_text='Separate items by comma', max_length=500, null=True),
        ),
    ]
