# Generated by Django 2.0.5 on 2018-08-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_dish_price'),
        ('restaurants', '0022_auto_20180803_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('dishes', models.ManyToManyField(related_name='dishes', to='menu.Dish')),
                ('restautant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
    ]
