# Generated by Django 2.0.5 on 2018-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(related_name='dishes_in_order', to='menu.Dish'),
        ),
    ]
