# Generated by Django 2.0.5 on 2018-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180804_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.IntegerField(choices=[(1, 'cash'), (2, 'card')], default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='menu.Dish'),
        ),
    ]
