# Generated by Django 2.0.5 on 2018-08-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_price'),
        ('orders', '0011_auto_20180807_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
        migrations.AddField(
            model_name='order',
            name='dishes32',
            field=models.ManyToManyField(related_name='dishes32_in_order', to='menu.Dish'),
        ),
    ]
