# Generated by Django 2.0.5 on 2018-08-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_price'),
        ('orders', '0012_auto_20180807_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dishes32',
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='menu.Dish'),
        ),
    ]
