# Generated by Django 2.0.5 on 2018-08-19 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_price'),
        ('orders', '0014_remove_order_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_to_order', to='menu.Dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_to_dish', to='orders.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(related_name='dishes_in_order', through='orders.DishQuantity', to='menu.Dish'),
        ),
    ]
