# Generated by Django 2.0.5 on 2018-08-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishquantity',
            name='dish_status',
            field=models.IntegerField(choices=[(0, 'Accepted'), (1, 'Is being cooked'), (2, 'Is ready to be served')], default=0),
        ),
    ]
