# Generated by Django 2.0.5 on 2018-08-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180823_1705'),
        ('orders', '0018_dishquantity_dish_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Accepted'), (1, 'Is being cooked'), (2, 'Is ready to be served')], default=0)),
                ('quantity', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_to_order', to='menu.Dish')),
            ],
        ),
        migrations.RemoveField(
            model_name='dishquantity',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dishquantity',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(related_name='dishes_in_order', through='orders.Item', to='menu.Dish'),
        ),
        migrations.DeleteModel(
            name='DishQuantity',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_to_dish', to='orders.Order'),
        ),
    ]
