# Generated by Django 2.0.5 on 2018-08-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180825_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dishes',
            new_name='items',
        ),
    ]
